<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b0738bf2-4faa-4219-acb3-1a7e133567e5</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.37" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlamboyantFnb.Domain\FlamboyantFnb.Domain.csproj" />
    <ProjectReference Include="..\FlamboyantFnb.Helper\FlamboyantFnb.Helper.csproj" />
    <ProjectReference Include="..\FlamboyantFnb.Infrastructure\FlamboyantFnb.Infrastructure.csproj" />
    <ProjectReference Include="..\FlamboyantFnb.Services\FlamboyantFnb.Services.csproj" />
  </ItemGroup>

</Project>
